### ISSUE TITLE
How to run the DDPG.py

### ISSUE THREAD

**Issue by ZHAOZHENZ** [davidtw0320/Resources-Allocation-in-The-Edge-Computing-Environment#5]
Where are ENV_NAME,I haven't looked for it and running with an error.

          env = gym.make(ENV_NAME)
NameError: name 'ENV_NAME' is not defined

How can I solve it?

**Comment by davidtw0320** [comment]
Hi, ZHAOZHENZ,
I've deleted unused code in the section. If you would like to run the code, just run `python3 src/run_this.py` under the root directory. You could see more detailed information in README.

**Comment by ZHAOZHENZ** [comment]
Hi，davidtw0320,
Thank you for answering my question,in addition,What attributes does each column represent about KASIT data?

**Comment by ZHAOZHENZ** [comment]
Hi,davidtw0320,Thank you for answering my question.Sorry to be a bother,I have a few more questions to ask you.Such as code documentation and data set description.

**Comment by RITUsulaam** [comment]
> Hi，davidtw0320,
> Thank you for answering my question,in addition,What attributes does each column represent about KASIT data?

same doubt let me know if you got to know that
thank you

**Comment by davidtw0320** [comment]
Hi,
In data/KAIST, the second column means the horizontal distance and the third column means the vertical distance according to a reference point. You may ignore the value in the first column.

**Comment by RITUsulaam** [comment]
Thank you David!!it helps a lot.
