### ISSUE TITLE
what exactly are the column names in KAIST mobility dataset

### ISSUE THREAD

**Issue by RITUsulaam** [davidtw0320/Resources-Allocation-in-The-Edge-Computing-Environment#6]
heyy can u explain what exactly are the column names in KAIST mobility dataset which u have used. I am having a prob with that.
Thank you for the code it is helpful

**Comment by davidtw0320** [comment]
Hi, 
In data/KAIST, the second column means the horizontal distance and  the third column means the vertical distance according to a reference point. You may ignore the value in the first column.
